### ISSUE TITLE
Regeneration does not consistently pop up.

### ISSUE THREAD

**Issue by GambetTV** [vtt-lair/simbuls-creature-aide#16]
Not sure why, there's no error messages or anything, but I would say about 70% of the time Regeneration doesn't work . It seems like the larger the combat is, or perhaps if there's multiple bad guys with regeneration, then it's less likely to work. Makes it really hard to rely on.

I'm on DnD5e 2.4.1 and Foundry v11.315.

EDIT: Seems to especially not work if the Combat Tracker is unlinked to a scene.

**Comment by TeacherBobK** [comment]
I was having the same problem as GambetTV so I was doing some trouble shooting.  I first confirmed that the other parts of the module were working correctly (lair actions, undead fort. etc) and they are.

I now assume that the text box wasn't showing up but behind the scene the game was trying to use the code.  I activated the extra debug info in the module setting and there is an error that says "Regeneration blocked by XXXX".  This was odd because the ability (in my case Inspiring Leader) wasnt active on the character.  That was until I looked in the effect tab and it was there.  Once I turned it off Regen started working again.  (Not sure why Inspiring Leader triggered it and not other effects)

So I brought up a monster that had regen.  A vampire.  Worked.  Gave it a buff - invisibility.  Stopped working.  The debug text said that Regen was being blocked by the concentration portion of invisibility.  Removed the concentration, which got rid of all the buffs, and it started working again.

Was it concentration?  I gave the vampire the Aid buff (a hp buff that doesnt require concentration) - blocked.
Was it a hp buff?  So I gave it Mage Armour (an AC)- blocked.
I used a different spell caster to cast bless on the Vampire - blocked.

It appears that the Regen part of your module does not like timed spell effects on the token (temporary buffs).  It doesnt matter if they originate from the creature itself or another actor.

Temporary Buffs prevent your module from going off.  Knowing this I am going to look at the regeneration.js code but I am not a programmer so I am unsure what I can do but i can look.  I hope this help you (VTT-Lair) in helping to fix your module; it is really helpful to me running a CoS campaign where lots of mobs have undead fort, lair actions, and regeneration.

I am on version 11.315 of Foundry and running DnD5e 3.2.1

---
To all those with the same problem, a temporary fix is to go into the module folder and find the regenerate.js file.  After backing it up you can put // infront of lines 73-80 using Notepad+.  This will prevent the module from checking to see if there is any effect blocking the regenerate ability.  Tested and works.  Since we can choose whether or not to apply the regeneration manually Im not sure I need it to be automated so I disabled that function.  You millage may vary.
