### ISSUE TITLE
Suggestion: Midi-QOL integration for undead fortitude

### ISSUE THREAD

**Issue by txm3278** [vtt-lair/simbuls-creature-aide#6]
When an undead creature with undead fortitude is dropped to 0 health, it would be nice if midi passed the full damage and whether the damage was from a crit or radiant to Simbul's Creature Aide before setting the health to 0. Simbul's Creature Aide would then send back if the creature died or is set to 0 health.

I posted this on both projects because I'm not sure if this module has api support for midi to accomplish this.

**Comment by tposney** [comment]
Midi already provides that information in the actor update. The options field contains a damageItem object
```
damageItem:   
actorId: "pzJ9EYxdisWdJ1lg"  
actorUuid: "Actor.pzJ9EYxdisWdJ1lg"  
appliedDamage: 29  
damageDetail: Array(3)  
0: Array(1)  
0: {damage: 12, type: 'slashing'}  
Array(1)  
0: {damage: 17, type: 'slashing'}  
hpDamage: 1  
newHP: 0  
newTempHP: 0  
oldHP: 1  
oldTempHP: 0  
sceneId: "jnNYTil6bDdmq1P8"  
tempDamage: 0  
tokenId: "r1FVsnRdroUAK6AG"  
tokenUuid: "Scene.jnNYTil6bDdmq1P8.Token.r1FVsnRdroUAK6AG"  
totalDamage: 29  
```

Version 10.0.22 will add a boolean critical flag to the damage item to allow testing for critical/radiant.

The following code will check for radiant/critical hits when passed the preUpdate options
```js
function checkRadiantCritical(options) {
    if (!options.damageItem) return false;
    if (options.damageItem.critical) return true;
    for (let di of options.damageItem.damageDetail) {
        for (let did of (di ?? [])) {
            if (did.type === "radiant") return true; // change this to use the module settings
        }
    }
    return false;
}
```
I did a test and changed
```js

static quickCheck(data, options) {
  if (UndeadFortitude.checkRadiantCritical(options)) {
      return {rollSave: false, saveDC: 0};
  } else
      return {rollSave: true, saveDc: data.baseDc + data.hpDelta
  }
}
```
Which auto rolls the save when needed.

Also an implementation suggestion. Rather than allowing the update to complete and the adding back one hp, can I suggest the following?
* The preUpdate hook should auto fail the update unless a module generated option is set - fortitudeSaveFailed is true.
* Then the rest of the hook does the checking for the save (same as it does now, but checking if the midi damageItem is present in the options) and if the save fails reapply the actor update, but this time setting ``options.fortitudeSaveFailed=true``.

That way the target only goes to 0 hp if the save fails, and the other effects of going to 0 hp, prone/unconscious/removing concentration never happen.
